[package]
authors = ["Tucker Hart <tucker.hart@yale.edu>"]
name = "memuse"
description = "Memuse system call."
version = "0.1.0"
build = "../../build.rs"

[dependencies.log]
version = "0.4.8"

[dependencies.task]
path = "../../kernel/task"